[package]
name = "surreal-client-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = "2.0"
client = { path = "../client" }
proc-macro2 = "1.0"
macro_magic = { version = "0.5", features = ["proc_support"] }
