[package]
name = "surreal-client-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0"
syn = "2.0"
# surreal-client = { path = "../surreal-client" }
proc-macro2 = "1.0"